spring:
  datasource:
    url: jdbc:mysql://140.143.198.246:3306/easy_test
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhengduo0612
    driver-class-name: com.mysql.jdbc.Driver
